### ISSUE TITLE
Incompatibility with IntelliJ IDEA 2023.3.2

### ISSUE THREAD

**Issue by aerfus** [epm-dev-priporov/idea-format-converter-plugin#3]
Hello @epm-dev-priporov,

the plugin is not compatible with the latest Intellij IDEA.
Could you please upgrade it?

Error message
```
Plugin 'Format-converter' (version '0.8.2') is not compatible
with the current version of the IDE, because it requires build 232.* or older
but the current build is IU-233.13135.103
```

Intellij IDEA information
```
IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
Kotlin: 233.13135.103-IJ
```

Thank you in advance,

**Comment by epm-dev-priporov** [comment]
@aerfus hello, thank you for the report. It's done and will be available in the upcoming update, now it's reviweing by JB, usually it takes 1-2 business days

**Comment by epm-dev-priporov** [comment]
@aerfus done. 
Available for downloading
